Add colors to central logging function

diff --git a/crossover b/crossover
--- a/crossover
+++ b/crossover
@@ -333,13 +333,15 @@ function log(){
             ;;
 
         warn)
-            echo "WARNING: $message" 1>&2
+            echo -n $(echoyellow "WARNING: ")
+            echo $(echowhite "$message") 1>&2
             echo -e "$message" >> "$LOG_FILE";            
             [ $opt_syslog -eq 1 ] && logger -t "$PROGNAME" -p daemon.warn "$message"
             ;;
         
         error)
-            echo "ERROR: $message" 1>&2
+            echo -n $(echored "ERROR: ")
+            echo $(echowhite "$message") 1>&2
             echo -e "$message" >> "$LOG_FILE";            
             [ $opt_syslog -eq 1 ] && logger -t "$PROGNAME" -p daemon.err "$message"
             ;;
